version: '3.7'

services:
  database:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: task
    volumes:
      - ./mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'

  app:
    build:
      context: .
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - '80:80'
